name: "say hello on each pull"
on: 
  push: # excecuted on all push
jobs: 
  say_hello: # first job déclaration 
    name: "say hello"
    runs-on: unbunto-latest
    steps: 
      # The follwing step execute a shell script 
      - name: "say hello"
        run: |
            echos "Hello, word !" 