name: "say hello on each pull"
on : 
  push : # excecuted on all push
jobs : 
  say_hello : # first job déclaration 
    name: "say hello"
    run-on : unbunto-latest
    steps: 
      # The follwing step execute a shell script 
      - name : "say hello"
      - run : |
            echos "Hello, word !" 
  dit_bonjour_a_jacob : # Premiere déclaration
    name: "dit bonjour"
    run-on: unbunto-latest
    steps:
      # The follwing step execute a shell script
      - name: "dit bonjour"
      - run : |
            echos "bonjour jacob"
