name: "say hello on each pull"
on: 
  push: # excecuted on all push
jobs: 
  say_hello: # first job declaration
    name: "say hello"
    run-on: ubuntu-latest
    steps: 
      # The following step execute a shell script
      - name: "say hello"
        runs: |
            echos "Hello, word !" 
  
